epoch_count: 40000
steps_per_epoch: 1
batch_size: 32
learning_rate: 0.0001

buffer_size: 10000
init_explore_rate: 1.0
final_explore_rate: 0.1
decay_steps: 10000

seed: 42
loss_freq: 20
update_target_freq: 100
evaluation_freq: 1000